//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConseilDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ConseilOBJ;
    
    public partial class ConseilEntitiesBis : DbContext
    {
        public ConseilEntitiesBis()
            : base("name=ConseilEntitiesBis")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Conseil> Conseils { get; set; }
        public DbSet<Habillage> Habillages { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Personne> Personnes { get; set; }
        public DbSet<Photo> Photos { get; set; }
        public DbSet<StatutHistorique> StatutHistoriques { get; set; }
        public DbSet<Style> Styles { get; set; }
        public DbSet<SuiviTelecharge> SuiviTelecharges { get; set; }
        public DbSet<TypeParam> TypeParams { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<Vetement> Vetements { get; set; }
    }
}
