//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConseilOBJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conseil
    {
        public Conseil()
        {
            this.Habillages = new HashSet<Habillage>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateLimite { get; set; }
        public Nullable<System.DateTime> DateAccepte { get; set; }
        public Nullable<System.DateTime> DateRefuse { get; set; }
        public int DemandeurId { get; set; }
        public int ConseillerId { get; set; }
        public int StyleId { get; set; }
        public int TypeId { get; set; }
    
        public virtual Personne Personne { get; set; }
        public virtual Personne Personne1 { get; set; }
        public virtual Style Style { get; set; }
        public virtual TypeParam TypeParam { get; set; }
        public virtual ICollection<Habillage> Habillages { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
