//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConseilOBJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public Personne()
        {
            this.Conseils = new HashSet<Conseil>();
            this.Conseils1 = new HashSet<Conseil>();
            this.Notifications = new HashSet<Notification>();
            this.Photos = new HashSet<Photo>();
            this.StatutHistoriques = new HashSet<StatutHistorique>();
            this.SuiviTelecharges = new HashSet<SuiviTelecharge>();
        }
    
        public int Id { get; set; }
        public string FBCode { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Pseudo { get; set; }
        public string Email { get; set; }
        public string Genre { get; set; }
        public Nullable<bool> AfficheInfo { get; set; }
        public Nullable<bool> EnvoiEmail { get; set; }
        public string MotPasse { get; set; }
    
        public virtual ICollection<Conseil> Conseils { get; set; }
        public virtual ICollection<Conseil> Conseils1 { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<StatutHistorique> StatutHistoriques { get; set; }
        public virtual ICollection<SuiviTelecharge> SuiviTelecharges { get; set; }
    }
}
