//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConseilOBJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuiviTelecharge
    {
        public System.DateTime Jour { get; set; }
        public int PersonneId { get; set; }
        public byte Compteur { get; set; }
    
        public virtual Personne Personne { get; set; }
    }
}
