//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConseilOBJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeParam
    {
        public TypeParam()
        {
            this.Conseils = new HashSet<Conseil>();
            this.Notifications = new HashSet<Notification>();
            this.Photos = new HashSet<Photo>();
            this.StatutHistoriques = new HashSet<StatutHistorique>();
            this.Vetements = new HashSet<Vetement>();
        }
    
        public int Id { get; set; }
        public byte TypeId { get; set; }
        public string TypeLib { get; set; }
        public string ParamCode { get; set; }
        public string ParamLib { get; set; }
    
        public virtual ICollection<Conseil> Conseils { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<StatutHistorique> StatutHistoriques { get; set; }
        public virtual ICollection<Vetement> Vetements { get; set; }
    }
}
